// Auto-generated color tokens from Figma
export const colors = {
  'color-tokens': '#ffffff', // Color Tokens,
  'color-tokens-page-header-window-marker-frame-b': '#a8d88f', // Color Tokens / .Page Header / Window Marker / Frame / b,
  'color-tokens-page-header-window-marker-frame-c-d': '#333333', // Color Tokens / .Page Header / Window Marker / Frame / c / d,
  'color-tokens-page-header-window-marker-frame-c-e': '#333333', // Color Tokens / .Page Header / Window Marker / Frame / c / e,
  'color-tokens-page-header-window-marker-frame-c-f': '#333333', // Color Tokens / .Page Header / Window Marker / Frame / c / f,
  'color-tokens-page-header-window-marker-frame-c-g': '#333333', // Color Tokens / .Page Header / Window Marker / Frame / c / g,
  'color-tokens-page-header-window-marker-frame-c-h': '#333333', // Color Tokens / .Page Header / Window Marker / Frame / c / h,
  'color-tokens-page-header-window-marker-frame-i': '#333333', // Color Tokens / .Page Header / Window Marker / Frame / i,
  'color-tokens-page-header-window-marker-frame-j': '#333333', // Color Tokens / .Page Header / Window Marker / Frame / j,
  'color-tokens-page-header-window-marker-frame-k': '#333333', // Color Tokens / .Page Header / Window Marker / Frame / k,
  'color-tokens-page-header-window-marker-design-library': '#000000', // Color Tokens / .Page Header / Window Marker / Design library,
  'color-tokens-page-header-section-meta-color---light-theme': '#000000', // Color Tokens / .Page Header / Section Meta / Color / Light theme,
  'color-tokens-title': '#0f1709', // Color Tokens / Title,
  'color-tokens-frame-3-text': '#000000', // Color Tokens / Frame 3 / Text,
  'color-tokens-header': '#000000', // Color Tokens / Header,
  'color-tokens-frame-11-section-header-header': '#0f1709', // Color Tokens / Frame 11 / .Section Header / Header,
  'color-tokens-frame-11-frame-9-color-block': '#ffffff', // Color Tokens / Frame 11 / Frame 9 / _color-block,
  'color-tokens-frame-11-frame-9-color-block-color': '#262626', // Color Tokens / Frame 11 / Frame 9 / _color-block / color,
  'color-tokens-frame-11-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 11 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-11-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 11 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-11-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 11 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-11-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 11 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-11-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 11 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-15-frame-12-section-header-header': '#0f1709', // Color Tokens / Frame 15 / Frame 12 / .Section Header / Header,
  'color-tokens-frame-15-frame-12-frame-9-color-block': '#ffffff', // Color Tokens / Frame 15 / Frame 12 / Frame 9 / _color-block,
  'color-tokens-frame-15-frame-12-frame-9-color-block-color': '#1a1a1a', // Color Tokens / Frame 15 / Frame 12 / Frame 9 / _color-block / color,
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 15 / Frame 12 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 15 / Frame 12 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 15 / Frame 12 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 15 / Frame 12 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 15 / Frame 12 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-15-frame-10-section-header-header': '#0f1709', // Color Tokens / Frame 15 / Frame 10 / .Section Header / Header,
  'color-tokens-frame-15-frame-10-frame-9-color-block': '#ffffff', // Color Tokens / Frame 15 / Frame 10 / Frame 9 / _color-block,
  'color-tokens-frame-15-frame-10-frame-9-color-block-color': '#0f1709', // Color Tokens / Frame 15 / Frame 10 / Frame 9 / _color-block / color,
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-label-label': '#0f1709', // Color Tokens / Frame 15 / Frame 10 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 15 / Frame 10 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-hex-hex': '#0f1709', // Color Tokens / Frame 15 / Frame 10 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-hex-code': '#0f1709', // Color Tokens / Frame 15 / Frame 10 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 15 / Frame 10 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-13-section-header-header': '#0f1709', // Color Tokens / Frame 13 / .Section Header / Header,
  'color-tokens-frame-13-frame-9-color-block': '#ffffff', // Color Tokens / Frame 13 / Frame 9 / _color-block,
  'color-tokens-frame-13-frame-9-color-block-color': '#1a4007', // Color Tokens / Frame 13 / Frame 9 / _color-block / color,
  'color-tokens-frame-13-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 13 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-13-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 13 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-13-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 13 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-13-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 13 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-13-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 13 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-16-frame-15-section-header-header': '#0f1709', // Color Tokens / Frame 16 / Frame 15 / .Section Header / Header,
  'color-tokens-frame-16-frame-15-frame-9-color-block': '#ffffff', // Color Tokens / Frame 16 / Frame 15 / Frame 9 / _color-block,
  'color-tokens-frame-16-frame-15-frame-9-color-block-color': '#a9e079', // Color Tokens / Frame 16 / Frame 15 / Frame 9 / _color-block / color,
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 16 / Frame 15 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 16 / Frame 15 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 16 / Frame 15 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 16 / Frame 15 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 16 / Frame 15 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-16-frame-14-section-header-header': '#0f1709', // Color Tokens / Frame 16 / Frame 14 / .Section Header / Header,
  'color-tokens-frame-16-frame-14-frame-9-color-block': '#ffffff', // Color Tokens / Frame 16 / Frame 14 / Frame 9 / _color-block,
  'color-tokens-frame-16-frame-14-frame-9-color-block-color': '#6baa32', // Color Tokens / Frame 16 / Frame 14 / Frame 9 / _color-block / color,
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 16 / Frame 14 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 16 / Frame 14 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 16 / Frame 14 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 16 / Frame 14 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 16 / Frame 14 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-18-frame-15-section-header-header': '#0f1709', // Color Tokens / Frame 18 / Frame 15 / .Section Header / Header,
  'color-tokens-frame-18-frame-15-frame-9-color-block': '#ffffff', // Color Tokens / Frame 18 / Frame 15 / Frame 9 / _color-block,
  'color-tokens-frame-18-frame-15-frame-9-color-block-color': '#f1eae6', // Color Tokens / Frame 18 / Frame 15 / Frame 9 / _color-block / color,
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 18 / Frame 15 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 18 / Frame 15 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 18 / Frame 15 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 18 / Frame 15 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 18 / Frame 15 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-18-frame-14-section-header-header': '#0f1709', // Color Tokens / Frame 18 / Frame 14 / .Section Header / Header,
  'color-tokens-frame-18-frame-14-frame-9-color-block': '#ffffff', // Color Tokens / Frame 18 / Frame 14 / Frame 9 / _color-block,
  'color-tokens-frame-18-frame-14-frame-9-color-block-color': '#f9e7da', // Color Tokens / Frame 18 / Frame 14 / Frame 9 / _color-block / color,
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 18 / Frame 14 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 18 / Frame 14 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 18 / Frame 14 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 18 / Frame 14 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 18 / Frame 14 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-18-frame-16-section-header-header': '#0f1709', // Color Tokens / Frame 18 / Frame 16 / .Section Header / Header,
  'color-tokens-frame-18-frame-16-frame-9-color-block': '#ffffff', // Color Tokens / Frame 18 / Frame 16 / Frame 9 / _color-block,
  'color-tokens-frame-18-frame-16-frame-9-color-block-color': '#ffeded', // Color Tokens / Frame 18 / Frame 16 / Frame 9 / _color-block / color,
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 18 / Frame 16 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 18 / Frame 16 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 18 / Frame 16 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 18 / Frame 16 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 18 / Frame 16 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-18-frame-17-section-header-header': '#0f1709', // Color Tokens / Frame 18 / Frame 17 / .Section Header / Header,
  'color-tokens-frame-18-frame-17-frame-9-color-block': '#ffffff', // Color Tokens / Frame 18 / Frame 17 / Frame 9 / _color-block,
  'color-tokens-frame-18-frame-17-frame-9-color-block-color': '#f0f8ff', // Color Tokens / Frame 18 / Frame 17 / Frame 9 / _color-block / color,
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 18 / Frame 17 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 18 / Frame 17 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 18 / Frame 17 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 18 / Frame 17 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 18 / Frame 17 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-18-frame-18-section-header-header': '#0f1709', // Color Tokens / Frame 18 / Frame 18 / .Section Header / Header,
  'color-tokens-frame-18-frame-18-frame-9-color-block': '#ffffff', // Color Tokens / Frame 18 / Frame 18 / Frame 9 / _color-block,
  'color-tokens-frame-18-frame-18-frame-9-color-block-color': '#faf2fe', // Color Tokens / Frame 18 / Frame 18 / Frame 9 / _color-block / color,
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 18 / Frame 18 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 18 / Frame 18 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 18 / Frame 18 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 18 / Frame 18 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 18 / Frame 18 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-18-frame-19-section-header-header': '#0f1709', // Color Tokens / Frame 18 / Frame 19 / .Section Header / Header,
  'color-tokens-frame-18-frame-19-frame-9-color-block': '#ffffff', // Color Tokens / Frame 18 / Frame 19 / Frame 9 / _color-block,
  'color-tokens-frame-18-frame-19-frame-9-color-block-color': '#fdf8e5', // Color Tokens / Frame 18 / Frame 19 / Frame 9 / _color-block / color,
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 18 / Frame 19 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 18 / Frame 19 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 18 / Frame 19 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 18 / Frame 19 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 18 / Frame 19 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-19-frame-15-section-header-header': '#0f1709', // Color Tokens / Frame 19 / Frame 15 / .Section Header / Header,
  'color-tokens-frame-19-frame-15-frame-9-color-block': '#ffffff', // Color Tokens / Frame 19 / Frame 15 / Frame 9 / _color-block,
  'color-tokens-frame-19-frame-15-frame-9-color-block-color': '#437dcf', // Color Tokens / Frame 19 / Frame 15 / Frame 9 / _color-block / color,
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 19 / Frame 15 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 19 / Frame 15 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 19 / Frame 15 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 19 / Frame 15 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 19 / Frame 15 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-19-frame-16-section-header-header': '#0f1709', // Color Tokens / Frame 19 / Frame 16 / .Section Header / Header,
  'color-tokens-frame-19-frame-16-frame-9-color-block': '#ffffff', // Color Tokens / Frame 19 / Frame 16 / Frame 9 / _color-block,
  'color-tokens-frame-19-frame-16-frame-9-color-block-color': '#309f56', // Color Tokens / Frame 19 / Frame 16 / Frame 9 / _color-block / color,
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 19 / Frame 16 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 19 / Frame 16 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 19 / Frame 16 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 19 / Frame 16 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 19 / Frame 16 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-19-frame-17-section-header-header': '#0f1709', // Color Tokens / Frame 19 / Frame 17 / .Section Header / Header,
  'color-tokens-frame-19-frame-17-frame-9-color-block': '#ffffff', // Color Tokens / Frame 19 / Frame 17 / Frame 9 / _color-block,
  'color-tokens-frame-19-frame-17-frame-9-color-block-color': '#e26815', // Color Tokens / Frame 19 / Frame 17 / Frame 9 / _color-block / color,
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 19 / Frame 17 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 19 / Frame 17 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 19 / Frame 17 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 19 / Frame 17 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 19 / Frame 17 / Frame 9 / _color-block / content / subtitle,
  'color-tokens-frame-19-frame-18-section-header-header': '#0f1709', // Color Tokens / Frame 19 / Frame 18 / .Section Header / Header,
  'color-tokens-frame-19-frame-18-frame-9-color-block': '#ffffff', // Color Tokens / Frame 19 / Frame 18 / Frame 9 / _color-block,
  'color-tokens-frame-19-frame-18-frame-9-color-block-color': '#da5050', // Color Tokens / Frame 19 / Frame 18 / Frame 9 / _color-block / color,
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-label-label': '#1a1a1a', // Color Tokens / Frame 19 / Frame 18 / Frame 9 / _color-block / content / Label / Label,
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-label-star-vector': '#fde28b', // Color Tokens / Frame 19 / Frame 18 / Frame 9 / _color-block / content / Label / star / Vector,
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-hex-hex': '#1a1a1a', // Color Tokens / Frame 19 / Frame 18 / Frame 9 / _color-block / content / Hex / HEX,
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-hex-code': '#1a1a1a', // Color Tokens / Frame 19 / Frame 18 / Frame 9 / _color-block / content / Hex / Code,
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-subtitle': '#595959', // Color Tokens / Frame 19 / Frame 18 / Frame 9 / _color-block / content / subtitle
} as const;

export const colorRgb = {
  'color-tokens': '255, 255, 255',
  'color-tokens-page-header-window-marker-frame-b': '168, 216, 143',
  'color-tokens-page-header-window-marker-frame-c-d': '51, 51, 51',
  'color-tokens-page-header-window-marker-frame-c-e': '51, 51, 51',
  'color-tokens-page-header-window-marker-frame-c-f': '51, 51, 51',
  'color-tokens-page-header-window-marker-frame-c-g': '51, 51, 51',
  'color-tokens-page-header-window-marker-frame-c-h': '51, 51, 51',
  'color-tokens-page-header-window-marker-frame-i': '51, 51, 51',
  'color-tokens-page-header-window-marker-frame-j': '51, 51, 51',
  'color-tokens-page-header-window-marker-frame-k': '51, 51, 51',
  'color-tokens-page-header-window-marker-design-library': '0, 0, 0',
  'color-tokens-page-header-section-meta-color---light-theme': '0, 0, 0',
  'color-tokens-title': '15, 23, 9',
  'color-tokens-frame-3-text': '0, 0, 0',
  'color-tokens-header': '0, 0, 0',
  'color-tokens-frame-11-section-header-header': '15, 23, 9',
  'color-tokens-frame-11-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-11-frame-9-color-block-color': '38, 38, 38',
  'color-tokens-frame-11-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-11-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-11-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-11-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-11-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-15-frame-12-section-header-header': '15, 23, 9',
  'color-tokens-frame-15-frame-12-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-15-frame-12-frame-9-color-block-color': '26, 26, 26',
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-15-frame-12-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-15-frame-10-section-header-header': '15, 23, 9',
  'color-tokens-frame-15-frame-10-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-15-frame-10-frame-9-color-block-color': '15, 23, 9',
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-label-label': '15, 23, 9',
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-hex-hex': '15, 23, 9',
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-hex-code': '15, 23, 9',
  'color-tokens-frame-15-frame-10-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-13-section-header-header': '15, 23, 9',
  'color-tokens-frame-13-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-13-frame-9-color-block-color': '26, 64, 7',
  'color-tokens-frame-13-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-13-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-13-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-13-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-13-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-16-frame-15-section-header-header': '15, 23, 9',
  'color-tokens-frame-16-frame-15-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-16-frame-15-frame-9-color-block-color': '169, 224, 121',
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-16-frame-15-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-16-frame-14-section-header-header': '15, 23, 9',
  'color-tokens-frame-16-frame-14-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-16-frame-14-frame-9-color-block-color': '107, 170, 50',
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-16-frame-14-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-18-frame-15-section-header-header': '15, 23, 9',
  'color-tokens-frame-18-frame-15-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-18-frame-15-frame-9-color-block-color': '241, 234, 230',
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-18-frame-15-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-18-frame-14-section-header-header': '15, 23, 9',
  'color-tokens-frame-18-frame-14-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-18-frame-14-frame-9-color-block-color': '249, 231, 218',
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-18-frame-14-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-18-frame-16-section-header-header': '15, 23, 9',
  'color-tokens-frame-18-frame-16-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-18-frame-16-frame-9-color-block-color': '255, 237, 237',
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-18-frame-16-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-18-frame-17-section-header-header': '15, 23, 9',
  'color-tokens-frame-18-frame-17-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-18-frame-17-frame-9-color-block-color': '240, 248, 255',
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-18-frame-17-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-18-frame-18-section-header-header': '15, 23, 9',
  'color-tokens-frame-18-frame-18-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-18-frame-18-frame-9-color-block-color': '250, 242, 254',
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-18-frame-18-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-18-frame-19-section-header-header': '15, 23, 9',
  'color-tokens-frame-18-frame-19-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-18-frame-19-frame-9-color-block-color': '253, 248, 229',
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-18-frame-19-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-19-frame-15-section-header-header': '15, 23, 9',
  'color-tokens-frame-19-frame-15-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-19-frame-15-frame-9-color-block-color': '67, 125, 207',
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-19-frame-15-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-19-frame-16-section-header-header': '15, 23, 9',
  'color-tokens-frame-19-frame-16-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-19-frame-16-frame-9-color-block-color': '48, 159, 86',
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-19-frame-16-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-19-frame-17-section-header-header': '15, 23, 9',
  'color-tokens-frame-19-frame-17-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-19-frame-17-frame-9-color-block-color': '226, 104, 21',
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-19-frame-17-frame-9-color-block-content-subtitle': '89, 89, 89',
  'color-tokens-frame-19-frame-18-section-header-header': '15, 23, 9',
  'color-tokens-frame-19-frame-18-frame-9-color-block': '255, 255, 255',
  'color-tokens-frame-19-frame-18-frame-9-color-block-color': '218, 80, 80',
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-label-label': '26, 26, 26',
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-label-star-vector': '253, 226, 139',
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-hex-hex': '26, 26, 26',
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-hex-code': '26, 26, 26',
  'color-tokens-frame-19-frame-18-frame-9-color-block-content-subtitle': '89, 89, 89'
} as const;

export type ColorToken = keyof typeof colors;

// Helper function to get color with opacity
export function getColorWithOpacity(color: ColorToken, opacity: number): string {
  return `rgba(${colorRgb[color]}, ${opacity})`;
}
